package:
  name: tomocam
  version: "1.0.0"

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python

about:
  license: XXX
