% test_all_util.m

list = {...
'arg_pair test', ...
'bspline_1d_coef test', ...
'bspline_1d_interp test', ...
'bspline_1d_synth test', ...
'cpu test', ...
'dft_sym_check test', ...
'downsample2 test', ...
'downsample3 test', ...
'embed test', ...
'fld_write test', ...
'fractional_delay test', ...
'hist_equal test', ...
'ifft_sym test', ...
'interp1_jump test', ...
'interp1_lagrange test', ...
'lloyd_max_hist test', ...
'masker test', ...
'min_cos_quad test', ...
'pad_into_center test', ...
'padn test', ...
'poisson test', ...
'reale test', ...
'reshaper test', ...
'sinc_periodic test', ...
'strum test', ...
'unpadn test', ...
'upsample_rep test', ...
'vararg_pair test'
};

run_mfile_local(list)
